### ISSUE TITLE
For JS/TS code that is not inside of a package that adds "type": "module", default to original behavior.

### ISSUE THREAD

**Issue by lifeiscontent** [softwareventures/resolve-typescript-plugin#19]
Seems that regardless of where the TS code exists (package or not) resolve-typescript-plugin will parse all TS expecting to find `.js` extensions.

should only lookup `.js` for modules that specific "type": "module"

**Comment by djcsdy** [comment]
Good idea. I will look into it. Thanks!

**Comment by lifeiscontent** [comment]
@djcsdy I figured out how to do this.

take a look here: https://gist.github.com/lifeiscontent/3eb5e54c6af46726e4d8b98a2021ed87

**Comment by djcsdy** [comment]
The functionality provided by this plugin is now built in to webpack, see https://github.com/softwareventures/resolve-typescript-plugin#obsolete
