### ISSUE TITLE
TypeScript cannot resolve type of this plugin itself

### ISSUE THREAD

**Issue by otakustay** [softwareventures/resolve-typescript-plugin#26]
1. Open [this TS playground](https://www.typescriptlang.org/play?target=99&moduleResolution=99#code/JYWwDg9gTgLgBABQDYFcDmwB2cBmUIhwDkUApgM4RIBupAtDAJ5gUDGUwYMdYqGmRANwAoYZlIB3RHywAKAJSCgA)
2. Change TS Config `Module` to `NodeNext`
3. See errors

![CleanShot 2022-01-06 at 13 49 19@2x](https://user-images.githubusercontent.com/639549/148335145-a6740acd-185e-4437-9c54-7069ce826b0d.png)

<img width="710" alt="image" src="https://user-images.githubusercontent.com/639549/148335163-90e66f62-7ecf-4808-b724-39d26cc62101.png">

**Comment by Cobertos** [comment]
I've been having to do in my `webpack.config.ts`, but not quite sure if it's an artifact of `ts-node` or not.

```typescript
import _ResolveTypeScriptPlugin from 'resolve-typescript-plugin';
// @ts-ignore
const ResolveTypeScriptPlugin = _ResolveTypeScriptPlugin.default;
```

**Comment by djcsdy** [comment]
Probably relates to #27, please watch that ticket for a fix.

**Comment by djcsdy** [comment]
@otakustay on #27:

> Having an error on `typescript@4.6.0-dev.20220114` with `"moduleResolution": "nodenext"`:
> 
> ```
> 9 import ResolveTypeScriptPlugin from 'resolve-typescript-plugin';
>                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> 
> Found 1 error in /Users/otakustay/Develop/reskript/packages/config-webpack/src/partials/base.ts:9
> ```
> 
> The `nodenext` module resolution won't automatically use `index.d.ts` as an entry, we need to put `"types": "./index.d.ts"` explicitly in `package.json`, I've manually added this to `node_modules/resolve-typescript-plugin/package.json` and everything works fine
