### ISSUE TITLE
Monorepo workspace dependencies and perf

### ISSUE THREAD

**Issue by vjpr** [softwareventures/resolve-typescript-plugin#55]
I have a monorepo and my workspace dependency paths match the `node_modules` regex. I'd like to limit it to just my workspace dependencies, and exclude any other `node_modules`.

I'm using pnpm and all my workspace packages can be found using https://www.npmjs.com/package/@pnpm/find-workspace-packages.

Providing some kind of `onlyInclude` option for paths would prevent having to do anything for 3rd party `node_modules`.

**Comment by djcsdy** [comment]
The functionality provided by this plugin is now built in to webpack, see https://github.com/softwareventures/resolve-typescript-plugin#obsolete
