### ISSUE TITLE
Obsolete

### ISSUE THREAD

**Issue by djcsdy** [softwareventures/resolve-typescript-plugin#66]
This project is probably obsoleted by https://github.com/webpack/enhanced-resolve/pull/351

Investigate and post an obsolescence notice if appropriate.

**Comment by fryorcraken** [comment]
From my tests, `extensionAlias` automatically applies to `node_modules` dependencies only which makes it unfit for the purpose of ESM support (as you don't need to mess up with the dependencies AFAIK).

**Comment by djcsdy** [comment]
Implemented in 49c896f.
